# Run E2E tests on the pull request, if it matches with specific label or file changes we'd like to observe.
name: ve2etests

on:
  pull_request:
    types: [synchronize, opened, reopened]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # report-results:
  #   name: E2E Results
  #   permissions:
  #     pull-requests: write
  #     contents: write
  #     pages: read
  #   uses: ./.github/workflows/ve2etests_results.yml
  #   with:
  #     bypass-e2e: false
  #     e2e-passed: true
  #   secrets: inherit

  # Reporter for non-bypassed case
  report-test-results:
    name: E2E Results (base)
    runs-on: ubuntu-latest
    steps:
      # not bypassed and e2e passed
      - if: ${{ true}}
        run: echo 'E2E Passed'
        # not bypassed and e2e failed
      - if: ${{ false}}
        run: |
          echo 'E2E Failed'
          exit 1
        # bypassed and approved
      - if: ${{ false }}
        run: echo 'E2E Bypass Approved'
        # bypassed and not approved
      - if: ${{ false }}
        run: |
          echo 'E2E Bypass Not Approved within 24 hours. Please rerun the workflow to re-request approval.'
          exit 1
