# Run E2E tests on the pull request, if it matches with specific label or file changes we'd like to observe.
name: ve2etests

on:
  pull_request:
    types: [synchronize, opened, reopened]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  report-results:
    name: E2E Results
    permissions:
      pull-requests: write
      contents: write
      pages: read
    uses: ./.github/workflows/ve2etests_results.yml
    with:
      bypass-e2e: false
      e2e-passed: true
    secrets: inherit
