# Report E2E Results
name: ve2etests-results

on:
  workflow_call:
    inputs:
      bypass-e2e:
        description: true if bypass-e2e label is applied
        required: true
        type: boolean
      e2e-passed:
        description: true is e2e passed successful
        required: true
        type: boolean

jobs:
  # Reporter for non-bypassed case
  report-test-results:
    name: E2E Results
    runs-on: ubuntu-latest
    steps:
      # not bypassed and e2e passed
      - if: ${{ !inputs.bypass-e2e && inputs.e2e-passed }}
        run: echo 'E2E Passed'
        # not bypassed and e2e failed
      - if: ${{ !inputs.bypass-e2e && !inputs.e2e-passed }}
        run: |
          echo 'E2E Failed'
          exit 1
        # bypassed and approved
      - if: ${{ inputs.bypass-e2e && true }}
        run: echo 'E2E Bypass Approved'
        # bypassed and not approved
      - if: ${{ inputs.bypass-e2e && false }}
        run: |
          echo 'E2E Bypass Not Approved within 24 hours. Please rerun the workflow to re-request approval.'
          exit 1
