# Run E2E tests on the pull request, if it matches with specific label or file changes we'd like to observe.
name: ve2etests

on:
  pull_request:
    types: [labeled, synchronize]
  workflow_call:
    inputs:
      print:
        type: string
        required: true

jobs:
  print-test:
    runs-on: ubuntu-latest
    steps:
      - name: print out test
        run: echo 'test ${{ github.event.inputs.print }}'

      - name: skip
        if: ${{ false }}
        run: echo 'skip'

  workflow-two:
    name: Use Workflow 2
    uses: ./.github/workflows/workflow2.yml
    with:
      print: 'test from workflow1'
    secrets: inherit
