# Run E2E tests on the pull request, if it matches with specific label or file changes we'd like to observe.
name: workflow

on:
  pull_request:
    types: [labeled, synchronize]

env:
  e2e-cache-key: e2e-cache-key-${{ github.ref }}
  e2e-cache-path: ${{ github.workspace }}/.e2e-cache

jobs:
  cache-results:
    name: Cache Passed Results
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Write Results to File
        # clear file and write new results
        run: |
          touch ${{ env.e2e-cache-path }}
          > ${{ env.e2e-cache-path }}
          echo "e2e-passed=${{ 'false' }}" >> ${{ env.e2e-cache-path }}
          echo "e2e-bypassed=${{ 'false' }}" >> ${{ env.e2e-cache-path }}
      - name: Cache Results
        uses: actions/upload-artifact@v4
        with:
          # cache by commit so new changes still need to be tested
          name: ${{ env.e2e-cache-key }}
          path: ${{ env.e2e-cache-path }}
          overwrite: true
