# Run E2E tests on the pull request, if it matches with specific label or file changes we'd like to observe.
name: workflow

on:
  issues:
    types: [edited]

jobs:
  log-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
