# Run E2E tests on the pull request, if it matches with specific label or file changes we'd like to observe.
name: workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  log-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Update OriginPath in Distribution Config
        id: update-origin-path
        uses: actions/github-script@v7
        with:
          script: |
            core.setOutput('ETag', 'test ETag');
            core.setOutput('distributionConfig', 'test ddistro config');

      - name: Print updated distribution config
        run: |
          echo "ETag: ${{ steps.update-origin-path.outputs.ETag }}"
          echo "updated distribution: ${{ steps.update-origin-path.outputs.distribution_config }}"
