# Run E2E tests on the pull request, if it matches with specific label or file changes we'd like to observe.
name: workflow

on:
  pull_request:
    types: [labeled, synchronize, opened]

env:
  e2e-cache-key: e2e-cache-key-${{ github.sha }}
  e2e-cache-path: ${{ github.workspace }}/.e2e-cache

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls -al
