# Run E2E tests on the pull request, if it matches with specific label or file changes we'd like to observe.
name: ve2etests

on:
  workflow_call:
    inputs:
      print:
        type: string
        required: true

jobs:
  print-test:
    runs-on: ubuntu-latest
    steps:
      - name: print out test
        run: echo 'test ${{ inputs.print }}'

      - name: skip
        if: ${{ false }}
        run: echo 'skip'
