# Run E2E tests on the pull request, if it matches with specific label or file changes we'd like to observe.
name: workflow

on:
  pull_request:
    types: [labeled, synchronize, opened]

jobs:
  check-changed-packages:
    name: Check if yarn.lock changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        # commit sha refers to v46.0.1: https://github.com/tj-actions/changed-files/commit/45fb12d7a8bedb4da42342e52fe054c6c2c3fd73
        uses: tj-actions/changed-files@45fb12d7a8bedb4da42342e52fe054c6c2c3fd73
